global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'jenkins-linux-workers'
    static_configs:
    - targets: [${linux_hosts}]
  - job_name: 'jenkins-windows-workers'
    static_configs:
    - targets: [${windows_hosts}]
  - job_name: 'jenkins-macos-workers'
    static_configs:
    - targets: [${macos_hosts}]
